name: jlips
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59687
title: jlips.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#48385f'
    - '#ffffff'
    - '#ee745d'
    - '#e8bb24'
    - '#60aca8'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
