name: jlips
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75459
title: jlips.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05564537760801613
  lightness: 0.668785436777398
  saturation: 0.586143117165193
  rhythmicContrast: 0.6471197733189911
purpose: []
